services:
  app:
    build: .
    depends_on:
      - db
    networks:
      - my_network
    env_file:  # Use .env file for environment variables
      - .env
    ports:
      - "8000:8000"

  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: debug
    networks:
      - my_network
    ports:
      - "5432:5432"
    # volumes:
    #   - db-data:/var/lib/postgresql/data  

networks:
  my_network:
    driver: bridge
    
# volumes:
#   db-data:
    


      



      
