"""create settings table

Revision ID: 2b73c61588d5
Revises: 48291c77b07d
Create Date: 2025-03-04 14:45:36.957565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b73c61588d5'
down_revision: Union[str, None] = '48291c77b07d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings_user_frequency',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('interval_seconds', sa.Integer(), nullable=False),
    sa.Column('times_per_day', sa.Integer(), nullable=False),
    sa.Column('specific_times', sa.JSON(), nullable=True),
    sa.Column('send_at_nighttime', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings_user_frequency')
    # ### end Alembic commands ###
