"""delete settings table

Revision ID: 48291c77b07d
Revises: 966f37e3e76d
Create Date: 2025-03-04 14:44:06.704256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48291c77b07d'
down_revision: Union[str, None] = '966f37e3e76d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings_user_frequency')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings_user_frequency',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('interval_seconds', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('times_per_day', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('specific_times', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('send_at_nighttime', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='settings_user_frequency_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='settings_user_frequency_pkey')
    )
    # ### end Alembic commands ###
