"""frequency_mode

Revision ID: c2306ee9c576
Revises: 3951933a1a3f
Create Date: 2025-03-03 17:49:17.120198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c2306ee9c576'
down_revision: Union[str, None] = '3951933a1a3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('INTERVAL', 'TIMES_PER_DAY', 'SPECIFIC_TIMES', name='frequencyenum').create(op.get_bind())
    op.add_column('users', sa.Column('frequency_mode', postgresql.ENUM('INTERVAL', 'TIMES_PER_DAY', 'SPECIFIC_TIMES', name='frequencyenum', create_type=False), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'frequency_mode')
    sa.Enum('INTERVAL', 'TIMES_PER_DAY', 'SPECIFIC_TIMES', name='frequencyenum').drop(op.get_bind())
    # ### end Alembic commands ###
