"""authors name rename

Revision ID: 8f41a95332c0
Revises: 9769580aabf0
Create Date: 2025-02-27 15:56:06.423206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f41a95332c0'
down_revision: Union[str, None] = '9769580aabf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('name', sa.String(), nullable=False))
    op.drop_constraint('authors_author_key', 'authors', type_='unique')
    op.create_unique_constraint(None, 'authors', ['name'])
    op.drop_column('authors', 'author')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'authors', type_='unique')
    op.create_unique_constraint('authors_author_key', 'authors', ['author'])
    op.drop_column('authors', 'name')
    # ### end Alembic commands ###
