"""quote.quote to quote.quote_text

Revision ID: e78c7684d0d1
Revises: 8f41a95332c0
Create Date: 2025-02-27 17:15:26.147429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e78c7684d0d1'
down_revision: Union[str, None] = '8f41a95332c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotes', sa.Column('quote_text', sa.Text(), nullable=False))
    op.drop_column('quotes', 'quote')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotes', sa.Column('quote', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('quotes', 'quote_text')
    # ### end Alembic commands ###
