"""default_author column for users table added

Revision ID: 9769580aabf0
Revises: f8df3657ad86
Create Date: 2025-02-27 15:20:28.012982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9769580aabf0'
down_revision: Union[str, None] = 'f8df3657ad86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('default_author', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'authors', ['default_author'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'default_author')
    # ### end Alembic commands ###
